name: Update README with Latest Release

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest release info
        id: get_release
        uses: actions/github-script@v3
        with:
          script: |
            const latestRelease = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return {
              tag_name: latestRelease.data.tag_name,
              html_url: latestRelease.data.html_url,
              assets: latestRelease.data.assets.map(asset => ({
                name: asset.name,
                download_url: asset.browser_download_url
              }))
            };
      - name: Update README.md
        run: |
          echo "## Latest Release: ${{ steps.get_release.outputs.tag_name }}" > temp_readme.md
          echo "[View on GitHub](${{ steps.get_release.outputs.html_url }})" >> temp_readme.md
          echo "" >> temp_readme.md
          echo "### Assets:" >> temp_readme.md
          for asset in "${{ steps.get_release.outputs.assets }}"; do
            name=$(echo $asset | jq -r '.name')
            url=$(echo $asset | jq -r '.download_url')
            echo "- [$name]($url)" >> temp_readme.md
          done
          echo "" >> temp_readme.md
          cat README.md >> temp_readme.md
          mv temp_readme.md README.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest release info"
          git push
