name: Update README with Latest and Pre-release Info

permissions:
  contents: write

on:
  release:
    types: [published, prereleased]
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest release info
        id: get_latest_release
        uses: actions/github-script@v3
        with:
          script: |
            const latestRelease = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput('tag_name', latestRelease.data.tag_name);
            core.setOutput('html_url', latestRelease.data.html_url);
            core.setOutput('assets', JSON.stringify(latestRelease.data.assets.map(asset => ({
              name: asset.name,
              download_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/releases/latest/download/${asset.name}`
            }))));
            core.setOutput('prerelease', latestRelease.data.prerelease);

      - name: Update README.md
        run: |
          # Start generating the README.md content
          echo "# v2raytun" > README.md
          echo "## Current Version: ${{ steps.get_latest_release.outputs.tag_name }}" >> README.md
          echo "" >> README.md

          # Add release information
          if [ "${{ steps.get_latest_release.outputs.prerelease }}" = "true" ]; then
            echo "## Pre-release: ${{ steps.get_latest_release.outputs.tag_name }}" >> README.md
            echo "[View on GitHub](${{ steps.get_latest_release.outputs.html_url }})" >> README.md
          else
            echo "## Latest Release" >> README.md
            echo "[View on GitHub](https://github.com/${{ github.repository }}/releases/latest)" >> README.md
          fi

          echo "" >> README.md
          echo "### Assets:" >> README.md
          
          assets='${{ steps.get_latest_release.outputs.assets }}'
          echo $assets | jq -c '.[]' | while read i; do
            name=$(echo $i | jq -r '.name')
            url=$(echo $i | jq -r '.download_url')
            echo "- [$name]($url)" >> README.md
          done
          
          echo "" >> README.md

          # Add static content about the project
          echo "## Project Information" >> README.md
          echo "- **Authors**: The creators of **v2raytun** are reachable via [Telegram](https://t.me/v2raytun)." >> README.md
          echo "- **Latest Version**: The latest version of **v2raytun** is available on [Google Play](https://play.google.com/store/apps/details?id=com.v2raytun.android)." >> README.md
          echo "- **Project Team**: Visit the project team’s website at [databridges.tech](https://databridges.tech)." >> README.md
          echo "- **Support**: For questions, please use the [Telegram chat](https://t.me/v2raytun). Only the latest versions are provided here for convenience." >> README.md

          echo "" >> README.md
          echo "### Contact" >> README.md
          echo "For any questions or inquiries, please contact us via [Telegram](https://t.me/v2raytun)." >> README.md

          # Add a random comment to ensure there is always a change
          echo "<!-- Updated on $(date) -->" >> README.md

      - name: Checkout to main branch
        run: |
          git checkout main

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest release info"
          git push
